heat_template_version: 2013-05-23
description:  Heat Flavor creation example
resources:
  test_flavor:
    type: OS::Nova::Flavor
    properties:
      ram: 1024
      vcpus: 1
      disk: 20
      swap: 2