heat_template_version: 2013-05-23

resources:
    MasterRouter:
        type: OS::Neutron::Router
        properties:
            external_gateway_info: { network: net04_ext }
    heat-inst-001_to_public-subnet_port:
        type: OS::Neutron::Port
        properties:
            fixed_ips:
                - subnet_id: { get_resource: public-subnet }
            network: { get_resource: public }
    test-est-subnet:
        type: OS::Neutron::Subnet
        properties:
            tenant_id: 7a0fa56ea34443219ffdbe958e32b82c
            allocation_pools: [{"start": "10.20.32.2",  "end": "10.20.32.254"}]
            cidr: 10.20.32.0/24
            network: 56194262-841d-4ddd-a665-f48df431bf76
            name: test-est-subnet
    internettester:
        type: OS::Nova::Server
        properties:
            image: 12135284-6a7a-4396-9675-4f6a4473a2bd
            name: internettester
            flavor: m1.micro
            networks:
                - network: net04
                - fixed_ip: 192.168.111.8, 10.20.2.144
    heat-inst-002:
        type: OS::Nova::Server
        properties:
            image: TestVM
            name: heat-inst-002
            flavor: m1.small
            networks:
                - port: { get_resource: heat-inst-002_to_private-subnet_port }
    heat-inst-001:
        type: OS::Nova::Server
        properties:
            image: TestVM
            name: heat-inst-001
            flavor: m1.small
            networks:
                - port: { get_resource: heat-inst-001_to_public-subnet_port }
    private-subnet:
        type: OS::Neutron::Subnet
        properties:
            network_id: { get_resource: private }
            cidr: 10.20.8.0/24
    new-ext-net-tester:
        type: OS::Nova::Server
        properties:
            image: 12135284-6a7a-4396-9675-4f6a4473a2bd
            name: new-ext-net-tester
            flavor: m1.micro
            networks:
                - network: TestNetwork
                - fixed_ip: 10.20.0.151
    net04_ext:
        type: OS::Neutron::Net
        properties:
            shared: False
            admin_state_up: True
            name: net04_ext
            tenant_id: 7a0fa56ea34443219ffdbe958e32b82c
    heat-inst-002_to_private-subnet_port:
        type: OS::Neutron::Port
        properties:
            fixed_ips:
                - subnet_id: { get_resource: private-subnet }
            network: { get_resource: private }
    net04__subnet:
        type: OS::Neutron::Subnet
        properties:
            tenant_id: 7a0fa56ea34443219ffdbe958e32b82c
            allocation_pools: [{"start": "192.168.111.2",  "end": "192.168.111.254"}]
            cidr: 192.168.111.0/24
            network: f374c0f0-7914-4d81-9649-9326448393c8
            name: net04__subnet
    private:
        type: OS::Neutron::Net
    net04_ext__subnet:
        type: OS::Neutron::Subnet
        properties:
            tenant_id: 7a0fa56ea34443219ffdbe958e32b82c
            allocation_pools: [{"start": "10.20.2.131",  "end": "10.20.2.254"}]
            cidr: 10.20.2.0/24
            network: 82ff2f3b-101b-4d04-8793-272436d29aa4
            name: net04_ext__subnet
    MasterRouter_to_public-subnet_interface:
        type: OS::Neutron::RouterInterface
        properties:
            router_id: { get_resource: MasterRouter}
            subnet: { get_resource: public-subnet }
    TestNetwork:
        type: OS::Neutron::Net
        properties:
            shared: False
            admin_state_up: True
            name: TestNetwork
            tenant_id: 7a0fa56ea34443219ffdbe958e32b82c
    TestUser_Subnet:
        type: OS::Neutron::Subnet
        properties:
            tenant_id: c2cd5843362f413c988c77696f74b708
            allocation_pools: [{"start": "10.20.7.2",  "end": "10.20.7.254"}]
            cidr: 10.20.7.0/24
            network: ef9eca20-d309-4b7a-9d04-652801ff79e8
            name: TestUser_Subnet
    net04:
        type: OS::Neutron::Net
        properties:
            shared: False
            admin_state_up: True
            name: net04
            tenant_id: 7a0fa56ea34443219ffdbe958e32b82c
    UserTestNetwork:
        type: OS::Neutron::Net
        properties:
            shared: False
            admin_state_up: True
            name: UserTestNetwork
            tenant_id: c2cd5843362f413c988c77696f74b708
    MasterRouter_to_private-subnet_interface:
        type: OS::Neutron::RouterInterface
        properties:
            router_id: { get_resource: MasterRouter}
            subnet: { get_resource: private-subnet }
    TestVolume:
        type: OS::Cinder::Volume
        properties:
            name: TestVolume
            volume_type: None
            size: 50
    test_ext:
        type: OS::Neutron::Net
        properties:
            shared: True
            admin_state_up: True
            name: test_ext
            tenant_id: 7a0fa56ea34443219ffdbe958e32b82c
    public-subnet:
        type: OS::Neutron::Subnet
        properties:
            network_id: { get_resource: public }
            cidr: 10.20.7.0/24
    public:
        type: OS::Neutron::Net
    TestNetwork_Subnet:
        type: OS::Neutron::Subnet
        properties:
            tenant_id: 7a0fa56ea34443219ffdbe958e32b82c
            allocation_pools: [{"start": "10.20.0.150",  "end": "10.20.0.200"}, {"start": "10.20.0.50",  "end": "10.20.0.100"}]
            cidr: 10.20.0.0/24
            network: 67699a34-c1b9-458b-9d0a-73297cb5b896
            name: TestNetwork_Subnet
