heat_template_version: 2013-05-23

resources:
    MasterRouter:
        type: OS::Neutron::Router
        properties:
            external_gateway_info: { network: net04_ext }
    MasterRouter_to_public-subnet_interface:
        type: OS::Neutron::RouterInterface
        properties:
            router_id: { get_resource: MasterRouter}
            subnet: { get_resource: public-subnet }
    heat-inst-001:
        type: OS::Nova::Server
        properties:
            image: TestVM
            name: heat-inst-001
            flavor: m1.small
            networks:
                - port: { get_resource: heat-inst-001_to_public-subnet_port }
    heat-inst-001_to_public-subnet_port:
        type: OS::Neutron::Port
        properties:
            fixed_ips:
                - subnet_id: { get_resource: public-subnet }
            network: { get_resource: public }
    public-subnet:
        type: OS::Neutron::Subnet
        properties:
            network_id: { get_resource: public }
            cidr: 10.20.31.0/24
    public:
        type: OS::Neutron::Net
