heat_template_version: 2013-05-23

resources:
    MasterRouter:
        type: OS::Neutron::Router
        properties:
            external_gateway_info: { network: net04_ext }
    MasterRouter_to_public-subnet_interface:
        type: OS::Neutron::RouterInterface
        properties:
            router_id: { get_resource: MasterRouter}
            subnet: { get_resource: public-subnet }
    heat-inst-002:
        type: OS::Nova::Server
        properties:
            image: TestVM
            name: heat-inst-002
            flavor: m1.small
            networks:
                - port: { get_resource: heat-inst-002_to_private-subnet_port }
    heat-inst-001:
        type: OS::Nova::Server
        properties:
            image: TestVM
            name: heat-inst-001
            flavor: m1.small
            networks:
                - port: { get_resource: heat-inst-001_to_public-subnet_port }
    MasterRouter_to_private-subnet_interface:
        type: OS::Neutron::RouterInterface
        properties:
            router_id: { get_resource: MasterRouter}
            subnet: { get_resource: private-subnet }
    private-subnet:
        type: OS::Neutron::Subnet
        properties:
            network_id: { get_resource: private }
            cidr: 10.20.8.0/24
    heat-inst-001_to_public-subnet_port:
        type: OS::Neutron::Port
        properties:
            fixed_ips:
                - subnet_id: { get_resource: public-subnet }
            network: { get_resource: public }
    heat-inst-002_to_private-subnet_port:
        type: OS::Neutron::Port
        properties:
            fixed_ips:
                - subnet_id: { get_resource: private-subnet }
            network: { get_resource: private }
    public-subnet:
        type: OS::Neutron::Subnet
        properties:
            network_id: { get_resource: public }
            cidr: 10.20.7.0/24
    public:
        type: OS::Neutron::Net
    private:
        type: OS::Neutron::Net
