heat_template_version: 2013-05-23
description: >
  A simple Heat template that spins up multiple instances and a private network (HOT template in YAML).
resources:
  heat_network_01:
    type: OS::Neutron::Net
    properties:
      admin_state_up: true
      name: heat-network-01
  heat_subnet_01:
    type: OS::Neutron::Subnet
    properties:
      name: heat-subnet-01
      cidr: 10.10.10.0/24
      dns_nameservers: [8.8.8.8, 4.2.2.2]
      enable_dhcp: true
      gateway_ip: 10.10.10.254
      network_id: { get_resource: heat_network_01 }
  heat_router_01:
    type: OS::Neutron::Router
    properties:
      admin_state_up: true
      name: heat-router-01
  heat_router_01_gw:
    type: OS::Neutron::RouterGateway
    properties:
      network_id: 82ff2f3b-101b-4d04-8793-272436d29aa4
      router_id: { get_resource: heat_router_01 }
  heat_router_int0:
    type: OS::Neutron::RouterInterface
    properties:
      router_id: { get_resource: heat_router_01 }
      subnet_id: { get_resource: heat_subnet_01 }
  instance0_port0:
    type: OS::Neutron::Port
    properties:
      admin_state_up: true
      network_id: { get_resource: heat_network_01 }
      security_groups:
        - default
  instance1_port0:
    type: OS::Neutron::Port
    properties:
      admin_state_up: true
      network_id: { get_resource: heat_network_01 }
      security_groups:
        - default
  instance0:
    type: OS::Nova::Server
    properties:
      name: heat-instance-01
      image: TestVM
      flavor: m1.small
      networks:
        - port: { get_resource: instance0_port0 }
  instance1:
    type: OS::Nova::Server
    properties:
      name: heat-instance-02
      image: TestVM
      flavor: m1.small
      networks:
        - port: { get_resource: instance1_port0 }