#####################################################################################################
# Script: compute_node.yaml
# Author: Kyle Robertson
# Date: September 18, 2015
# Company: Worlcom Exchange Inc.
# Description: A HEAT template that deploys the compute nodes in the TORQUE PBS job schedular architecture. 
# This node runs the pbs_mom service and all the users jobs   
#####################################################################################################


heat_template_version: 2014-10-16
description: Homogenous compute cluster

parameters:
  image:
    type: string
    description: Image used for servers
  key_name:
    type: string
    description: SSH key to connect to the servers
  flavor:
    type: string
    description: flavor used by the servers
  network:
    type: string
    description: Network used by the server
  sec_group:
    type: string
    description: Security group for headnodes
  metadata:
    type: json
    description: Information about the autoscaling stack this server resource is a part of

resources:
  server:
    type: OS::Nova::Server
    properties:
      name: compute_node
      flavor: {get_param: flavor}
      image: {get_param: image}
      key_name: {get_param: key_name}
      metadata: {get_param: metadata}
      networks: [network: {get_param: network}]
      security_groups: [{get_param: sec_group}]
      user_data_format: RAW
      user_data: |
        #cloud-config
        users:
          - name: demo
            groups: sudo
            shell: /bin/bash
            sudo: ['ALL=(ALL) NOPASSWD:ALL']
        chpasswd:
          list: |
            demo:demo-password
            root:root-password
          expire: False
        ssh_pwauth: True
        runcmd:
          - touch /test.txt
          - echo "!!!!!!!!!!!!!THIS IS CLOUD INIT!!!!!!!!!!!!!"
          - sudo yum install stress

outputs:
  server_ip:
    description: IP Address of the load-balanced server.
    value: { get_attr: [server, first_address] }